apply plugin: 'com.android.application'
apply from: '../gradle/outputfilename.gradle'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "de.saschawillems.vulkangltfloadingrmlui"
        minSdkVersion 33
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++20"
                def rmluiThirdparty = new File(project.projectDir, '../../../external/RmlUi/thirdparty').absolutePath.replace('\\', '/')
                arguments "-DANDROID_STL=c++_shared", '-DANDROID_TOOLCHAIN=clang', '-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON',
                    "-DCMAKE_MODULE_PATH=${rmluiThirdparty}"
            }
        }
    }
    sourceSets {
        main.assets.srcDirs = ['assets']
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

task copyTask {
    copy {
        from '../../common/res/drawable'
        into "src/main/res/drawable"
        include 'icon.png'
    }

    copy {
        from rootProject.ext.shaderPath + 'glsl/base'
        into 'assets/shaders/glsl/base'
        include '*.spv'
    }

    copy {
        from rootProject.ext.shaderPath + 'glsl/gltfloading'
        into 'assets/shaders/glsl/gltfloading'
        include '*.*'
    }

    copy {
        from rootProject.ext.shaderPath + 'glsl/gltfloading_rmlui'
        into 'assets/shaders/glsl/gltfloading_rmlui'
        include '*.*'
    }

    copy {
        from rootProject.ext.assetPath + 'models/FlightHelmet/glTF'
        into 'assets/models/FlightHelmet/glTF'
        include '*.*'
    }

    copy {
        from '../../../examples/gltfloading_rmlui/data'
        into 'assets/overlay'
        include '**/*'
    }

    copy {
        from '../../../external/RmlUi/Samples/assets'
        into 'assets/rmlui_assets'
        include '**/*'
    }
}

preBuild.dependsOn copyTask
